// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFF352h33xcHd5qaLGm65D5VHW_iQhBPY',
    appId: '1:97898912615:web:f4084e053acc959efcadc2',
    messagingSenderId: '97898912615',
    projectId: 'ultra-zenith-112233',
    authDomain: 'ultra-zenith-112233.firebaseapp.com',
    storageBucket: 'ultra-zenith-112233.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2n8BxP8pJZAaPZCrmMMNa_D4okhvN8Xs',
    appId: '1:97898912615:android:2f74aa894c211d59fcadc2',
    messagingSenderId: '97898912615',
    projectId: 'ultra-zenith-112233',
    storageBucket: 'ultra-zenith-112233.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_klWiyT8MNzX9f7R-QvXEVkOUX1XbWQg',
    appId: '1:97898912615:ios:719a4035775c007cfcadc2',
    messagingSenderId: '97898912615',
    projectId: 'ultra-zenith-112233',
    storageBucket: 'ultra-zenith-112233.appspot.com',
    iosBundleId: 'com.example.learnALanguageBuddyAppTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_klWiyT8MNzX9f7R-QvXEVkOUX1XbWQg',
    appId: '1:97898912615:ios:719a4035775c007cfcadc2',
    messagingSenderId: '97898912615',
    projectId: 'ultra-zenith-112233',
    storageBucket: 'ultra-zenith-112233.appspot.com',
    iosBundleId: 'com.example.learnALanguageBuddyAppTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFF352h33xcHd5qaLGm65D5VHW_iQhBPY',
    appId: '1:97898912615:web:f4084e053acc959efcadc2',
    messagingSenderId: '97898912615',
    projectId: 'ultra-zenith-112233',
    authDomain: 'ultra-zenith-112233.firebaseapp.com',
    storageBucket: 'ultra-zenith-112233.appspot.com',
  );

}